# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mkdir -p build/logs
      - run: sudo apt-get update -y -qq

      # GD install
      - run: sudo apt-get install -y -qq libfreetype6-dev libpng-dev libjpeg-dev
      - run: sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
      - run: sudo docker-php-ext-install gd

      # ImageMagick install
      - run: sudo apt-get install -y -qq imagemagick
      - run: yes | sudo pecl install -f imagick
      - run: sudo docker-php-ext-enable imagick

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: vendor/bin/phpcs --warning-severity=6 --standard=PSR2 ./src
      - run: vendor/bin/phpcs --warning-severity=6 --standard=PSR2 ./tests
      - run: vendor/bin/phpunit
      - run: php vendor/bin/php-coveralls
